### ISSUE TITLE
SIGINT isnt exiting immediately

### ISSUE THREAD

**Issue by max-mapper** [maxogden/punzip#1]
to reproduce, run this and CTRL+C after a few seconds: `punzip http://download.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Medicare-Provider-Charge-Data/Downloads/PartD_Prescriber_PUF_NPI_DRUG_13.zip --entry=2 | csv-parser --separator=$'\t'`

@mafintosh any ideas?

**Comment by max-mapper** [comment]
hmm I even tried putting `require('epipebomb')` into both `punzip` and `csv-parser` but I am still getting

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at Object.exports._errnoException (util.js:843:11)
    at exports._exceptionWithHostPort (util.js:866:20)
    at WriteWrap.afterWrite (net.js:746:14)
```

when exiting the above pipeline
